name: CI - Test Source Code and Docker Image

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  # Step 2: Build Docker Image
  build-docker-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} # Use the token here

      - name: Build Docker Image
        run: |
          cd api
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cs360_back:latest .

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cs360_back:latest

      - name: Build Docker Image back
        run: |
          cd client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cs360_front:latest .

      - name: Push Docker Image to DockerHub
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/cs360_front:latest
            
  # Step 3: Test Docker Image
  test-docker-image:
    needs: build-docker-back
    runs-on: ubuntu-latest

    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} # Use the token here

      - name: Pull and Run Docker Image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/cs360_back:latest
          docker run -d --name test-container ${{ secrets.DOCKER_USERNAME }}/cs360_back:latest

      - name: Run Automated Tests in Docker Container
        run: |
          docker exec test-container yarn test 

      - name: Clean Up Docker Container
        run: |
          docker stop test-container
          docker rm test-container